version: 2
jobs:
    build:
        docker:
            - image: debian:sid-slim
        steps:
            - checkout
            - run: |
                apt-get update
                apt-get install -y git gcc cmake libeigen3-dev libgmp-dev libgmpxx4ldbl libumfpack5 libmpfr-dev libboost-dev libboost-thread-dev python3-dev python3-venv python3-nose python3-numpy python3-scipy python3-setuptools && apt-get clean
            - run: git checkout $CIRCLE_BRANCH
            - run: git submodule sync
            - run: git submodule update --init
            - run: python3 -m venv py_env
            - run:
                workding_directory: $CIRCLE_WORKING_DIRECTORY
                command: |
                    source py_env/bin/activate
                    mkdir -p third_party/build
                    mkdir -p build
                    pip install -r python/requirements.txt
                    cd third_party/build
                    cmake .. && make -j 4 && make install
                    cd ../../build
                    cmake .. && make
                    make all_tests
    "py3.6":
        machine: true
        steps:
            - checkout
            - run: |
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker build -t qnzhou/pymesh:py3.6 docker/py3.6
                docker push qnzhou/pymesh:py3.6
    "py3.6-slim":
        machine: true
        steps:
            - checkout
            - run: |
                cd docker/py3.6-slim
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                ./build.sh
                docker push qnzhou/pymesh:py3.6-slim
                docker tag qnzhou/pymesh:py3.6-slim qnzhou/pymesh
                docker push qnzhou/pymesh
    "py2.7":
        machine: true
        steps:
            - checkout
            - run: |
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker build -t qnzhou/pymesh:py2.7 docker/py2.7
                docker push qnzhou/pymesh:py2.7
    "py2.7-slim":
        machine: true
        steps:
            - checkout
            - run: |
                cd docker/py2.7-slim
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                ./build.sh
                docker push qnzhou/pymesh:py2.7-slim

workflows:
    version: 2
    build_and_test_and_deploy:
        jobs:
            - build
            - "py3.6":
                requires:
                    - build
                filters:
                    branches:
                        only: master
            - "py2.7":
                requires:
                    - build
                filters:
                    branches:
                        only: master
            - "py3.6-slim":
                requires:
                    - "py3.6"
                filters:
                    branches:
                        only: master
            - "py2.7-slim":
                requires:
                    - "py2.7"
                filters:
                    branches:
                        only: master

